### ISSUE TITLE
TEI header

### ISSUE THREAD

**Issue by gaborpalko** [COST-ELTeC/ELTeC-hun#2]
Dear @lb42 , 
the header is not valid, true. 
We could not deal with the subtitle which is missing from the specification. We have chosen the solution:
<title type="main">Jávor orvos és szolgája, Bakator Ambrus</title>
<title type="sub">Szeszélyes regény</title>
<title type="sub">ELTeC edition</title>
According to the specification we should have done like this:
<title>Jávor orvos és szolgája, Bakator Ambrus : ELTeC edition</title>
Or:
<title>Jávor orvos és szolgája, Bakator Ambrus. Szeszélyes regény : ELTeC edition</title>
Both are misleading I think.
pg

**Comment by lb42** [comment]
It's also invalid because you have a typo (reps instead of resp). But I don't understand: why do you think the version recommended by our specification is misleading? Why do you want to subdivide the title in this way?  Hungarian Wikipedia gives the title of the work as Jávor orvos és szolgája Bakator Ambrus  -- with no comma. The subtitle "Szeszélyes regény" perhaps belongs in the source description, but it's not necessary here, I think.

**Comment by gaborpalko** [comment]
Maybe we should rely on a more trustworthy source than Wikipedia :)
The subtitle is important in this case, if you take a look at any institutional bibliographical description of the book, the subtitle is not missing:
http://mek.oszk.hu/08100/08163/index.xml
http://nektar.oszk.hu/hu/manifestation/1572923
Even Google Books:  
Jávor orvos és szolgája, Bakator Ambrus: szeszélyes regény, Volumes 1-2
By András Fáy
I am quite sure there will be similar examples where the subtitle is important.

**Comment by lb42** [comment]
Sure, I have no objection to including the subtitle in the source description. But we are making up the title in the titlestatement, so I think we should keep it simple, like the author field.
